### PR TITLE
Main Activity no longer uses a string to construct initial garden

### PR DESCRIPTION
**Pull request by libertylocked**
Got rid of the default string and used code generated garden instead

### CODE REVIEW

**Comment by grselker** [comment]
Wenchao, In MainActivityTest.java, testLoadDefaultGarden() and testLoadGarden() fail as a result of the changes that Muneeb made in #49. However, in this pull request, you are making changes that should cause those tests to pass. Those tests will definitely have to pass before this pull request is merged.

**Comment by libertylocked** [comment]
why isn't this PR merged?

**Comment by grselker** [comment]
For one it is assigned to Muneeb, so he is going to be the one to merge it. But I need you to make absolutely certain that your changes integrate well with Muneeb's changes in #49.

**Comment by mra48** [comment]
It looks good although it doesnt take pull request #49 into account but that is ok because those changes will come later. I will merge it.

**Pull request merged**
