### PR TITLE
Feature/new plant part3

### PR DESCRIPTION
**Pull request by grselker**
This pull request adds functionality for Cancel, and View Species Info, and sets the TextView to the species name when a plant is added. It also makes it so a plant is not drawn before the user taps. Also, the hack lines were taken out.

### CODE REVIEW

**Comment by grselker** [comment]
Wenchao, I am making some more changes for this pull request. I will let you know when it is ready to go. Please look at it as soon as possible after I finish making changes.

**Comment by grselker** [comment]
Wenchao, I have decided that I am done with my changes now. I was going to add a dialogue for adding date information when a plant is added to the garden, but I decided that it needs to be another feature branch.

**Comment by grselker** [comment]
I think I left in a line if (speciesName == null) speciesName = "sunflower"; on line 48 of GardenDrawingActivity.java so that you can test adding new plants to the garden. You should be able to see them just fine now since we are using real colors.

**Comment by chuckie512** [comment]
your changes are clean and easy to understand.
Tests are still passing.
App builds and runs.
I'm not seeing any clear issues when adding a plant.

only thing: before a plant is confirmed, the logcat is going crazy with debug logs of onDraw like it's in a very quick running loop.

**Comment by grselker** [comment]
I will comment out the logging -- give me a sec

**Comment by chuckie512** [comment]
BTW logs are good, logs in a loop, not so much

**Comment by grselker** [comment]
I believe the trouble making log was in onDraw() which gets called in a loop...I am going to leave the Log that was for each tap when adding a plant unless you want me to remove that -- it prints out much less rapidly than the onDraw() log.

**Comment by chuckie512** [comment]
the other logs are good

**Comment by chuckie512** [comment]
ok looks good!

**Comment by grselker** [comment]
Great!

**Pull request merged**
