### PR TITLE
Feature/integrate garden engine garden drawing

### PR DESCRIPTION
**Pull request by grselker**
This pull request does not add anything new other than it incorporates the GardenInterface into the GardenDrawingActivity and such. It should appear exactly as it did before the changes. I created a lot of comments and tests. Let me know if anyone thinks I need more tests or comments.

### CODE REVIEW

**Comment by mra48** [comment]
I am currently looking through and everything looks pretty good. I have a question so far about Gardenview,java. Any reason why you changed a lot of declarations from private to protected?

**Comment by mra48** [comment]
Also, why did you move the tests? Why did they belong in the file that they got moved to? Because i think i see some correlation between the tests and the filename but I dont know your exact reasoning from the comments you submitted along with the commit.

**Comment by mra48** [comment]
I finished looking at the rest of it and it looks pretty good. Can you still answer the questions i asked earlier because I still dont know why you moved the tests or changed from private to protected

**Comment by grselker** [comment]
I changed declarations to protected so that I could set stuff up in my tests. A lot of the state in GardenView depends on the fact that the GardenDrawingActivity will not be opened until after the MainActivity has been opened. I talked to Laboon after class yesterday, and he said that it made sense in this case.

**Comment by grselker** [comment]
Initially the tests were in a different file because I was testing a private inner class of GardenView. The last time my code was merged, the methods under test in the removed test file were actually in GardenView and not in the inner class. I just forgot to consolidate the last time.

**Pull request merged**
