### PR TITLE
Feature/updated garden interface

### PR DESCRIPTION
**Pull request by chuckie512**
@mra48 's changes (that he had in another fork) moved into a branch by @grselker , then updated with some minor changes.

I don't have the right environment setup on this machine to run the tests (went home for the weekend) but it should all still work.

see #17 for past discussion 

This PR address issue #7

### CODE REVIEW

**Comment by chuckie512** [comment]
so I fixed the compile problems, and reduced the number of compile warnings

**Comment by chuckie512** [comment]
This is not yet ready to merge.  Added a test for starting from an empty garden and program crashes.  I'm investigating but for now I'm going to close this PR.

**Comment by chuckie512** [comment]
reopened with the bug I found fixed

**Comment by grselker** [comment]
I am going to code review / test this code

**Comment by grselker** [comment]
Any chance we could get a comment for each of the tests in GardenTest.java giving like a one-line summary?

**Comment by chuckie512** [comment]
That's mostly Muneeb's doing (the lack of comments that is, a minority of this was written by me) if you know what's going on feel free to add comments

**Comment by chuckie512** [comment]
Muneeb also said he'd add javadoc in a future PR

**Comment by grselker** [comment]
Chuck, is there any way to create an issue or something to add more documentation for this. I think that we probably need to merge this now, but more documentation will be required before the end of the sprint.

**Comment by chuckie512** [comment]
I'll create a new issue and close issue #7

**Comment by grselker** [comment]
Sounds like a plan.

**Comment by grselker** [comment]
Actually -- don't close that refactoring issue

**Comment by chuckie512** [comment]
issue #20 opened due to problems in this PR

**Comment by grselker** [comment]
Passes code review. However, issue #20 must be completed by the end of this sprint, and it would be really good to do some refactoring. In specific:
gardenToString() turn the contents into two or three separate methods -- this method is a bit too long
stringToGarden() turn the contents into several methods -- this method is really too long

**Comment by grselker** [comment]
I will now run the app and tests

**Comment by grselker** [comment]
Bad news -- "Unfortunately GardenApp has stopped" ... as soon as you launch it.
The source of this is stringToGarden()

Caused by: java.lang.NumberFormatException: Invalid int: "2:tomato:half:23:44:1234:sunflower:full:34:54:1245:1:2:3:sunflower"
at com.cs1530_group1.gardenapp.Garden.stringToGarden(Garden.java:95)
at com.cs1530_group1.gardenapp.MainActivity.onCreate(MainActivity.java:33)

**Comment by grselker** [comment]
I love what github has done to the string

**Comment by grselker** [comment]
This branch cannot be merged until this has been fixed. The app compiles, but does not really run.

**Comment by chuckie512** [comment]
lol github :tongue: 

but I think i know the problem.  can you change the line in MainActivity that creates a garden from a string to use one of the Strings from the test?

**Comment by grselker** [comment]
I will try that

**Comment by grselker** [comment]
Ok -- so was that just a trash string that did not include all the data necessary to make the two plants?

**Comment by chuckie512** [comment]
yes, @mra48 's previous implementation made me use a hard coded string so we had something to work with.  It seems that format changed in this update

**Comment by grselker** [comment]
Ok -- all is not wrong with the world...we still may be able to merge this -- changed the string and it is up and running

**Comment by grselker** [comment]
Sorry for overreacting

**Comment by chuckie512** [comment]
lol it's fine I really should have caught that

**Comment by chuckie512** [comment]
+1 for code reviews

**Comment by grselker** [comment]
So you change that line and push it?

**Comment by grselker** [comment]
I should not push it since I am code reviewing it...

**Comment by chuckie512** [comment]
kk, give me a sec to checkout the branch

**Comment by chuckie512** [comment]
fixed the hard coded string

**Comment by grselker** [comment]
Technically testSets() should be like seven sets -- This should be fixed as part of refactoring

**Comment by chuckie512** [comment]
agreed

**Comment by grselker** [comment]
All tests pass and the app runs. Here is the summary of things that need to be changed. I believe that we will lose points on code if these are not addressed:
issue #20 by the end of the sprint
code refactoring (see if issue #7 still applies):
1. gardenToString() turn the contents into two or three separate methods -- this method is a bit too long
2. testSets() should be like seven or eight separate tests
3. stringToGarden() turn the contents into several methods -- this method is really too long

**Comment by chuckie512** [comment]
it may be a good idea to update issues #7 and #20 with your findings

**Comment by grselker** [comment]
I will update those tonight

**Comment by grselker** [comment]
I have closed #7 and created #21 for the refactoring

**Comment by grselker** [comment]
I don't think there is anything to more to say on #20. Good job everyone. Now let's get some user stories done and bugs fixed.

**Pull request merged**
