### PR TITLE
made changes that integrate the new FileOperation.java and the updated Garden.java into the MainActivity

### PR DESCRIPTION
**Pull request by chuckie512**
fixes to the main activity to make it work with the new classes.

### CODE REVIEW

**Comment by libertylocked** [comment]
Maybe break down the big method into small methods and add tests for these.
Also I don't think it is a good idea to wrap it in try catch. Maybe the FileOperation should have a bool fileExists(fileName)
Also the app needs to store the data back if it has not been created.

**Comment by chuckie512** [comment]
The big method has been split into smaller parts
saving the data is only going to be after changes occur, so not on the main activity

**Comment by chuckie512** [comment]
saving the data is only going to be after changes occur

**Comment by libertylocked** [comment]
the file has to be created if it does not exist - to ensure consistency
Otherwise you will have some data that there is no record of such data on storage.

**Comment by chuckie512** [comment]
ok, I'll write that in.

**Comment by libertylocked** [comment]
Use FileOperation.exists() to check if the garden data exists - if not, create such file.
Then read data from the file.
Then try catch block can be used to catch errors that are not FileNotFoundExceptions.

It should be easier to break it down into methods, e.g. void setUpGardenDataFile(), Garden readGardenDataFile().
Need tests for those.

**Comment by chuckie512** [comment]
rebased and updated to use .exists()

**Comment by chuckie512** [comment]
onCreate has been split up into smaller parts
hold up, looks like i screwed up the rebase (UGH)

**Comment by chuckie512** [comment]
hold up, looks like i screwed up the rebase (UGH)

**Comment by libertylocked** [comment]
Maybe should have merged master into your branch instead of rebasing?
This is kind of messy

**Comment by chuckie512** [comment]
yeah, i just saw that in the diff
let me revert to pre-rebase

**Comment by chuckie512** [comment]
let me revert to pre-rebase

**Comment by LibertyLocked** [comment]
Let me chunk the comments for you.
~~There are way too many - comments are not IMs. This is kind of annoying~~

**Comment by chuckie512** [comment]
undid rebase and fixed that mess

**Comment by chuckie512** [comment]
ok @LibertyLocked , should be good now i think

**Comment by libertylocked** [comment]
What is the test procedure for this feature?
Doesn't seem it can be easily tested.

**Comment by chuckie512** [comment]
I don't know if we can setup a unit test as App.java cannot be initialized without the whole app being launched. (as it extends the Application class)

**Comment by chuckie512** [comment]
Added Log.v statements to help with seeing what is going when when running in the emulator.  everything seems to be working correctly.  creates a default garden on first launch, and loads that save on all successive launches.

**Comment by chuckie512** [comment]
added tests, which are showing an error that maybe from a different section of the code.  The Strings compared in the tests are Identical except for all 24hr time is in 12hr format.  None of the code in this PR would be able to make such a change

**Comment by chuckie512** [comment]
tests are now included

**Pull request merged**
