### PR TITLE
Got rid of time in Date object

### PR DESCRIPTION
**Pull request by mra48**
Only the day, month, and year are required, and the time is no longer
required or actually used. Updated the tests in Garden.java to reflect this

### CODE REVIEW

**Comment by grselker** [comment]
I will be code reviewing this pull request. I have run all the tests, and they pass. Also, the app still compiles and runs.

**Comment by mra48** [comment]
Sweet

**Comment by grselker** [comment]
Changes and comments look good. Let's merge this.

**Comment by mra48** [comment]
ok thanks

**Pull request merged**
