### PR TITLE
Changed pruneDate from Date to String

### PR DESCRIPTION
**Pull request by mra48**
I changed pruneDate from a Date object to a String. I
also ran the tests and created new tests for this change.

### CODE REVIEW

**Comment by grselker** [comment]
I am code reviewing the files you changed. Almost everything looks good and makes sense, except I don't understand how you removed the "21:22:13" time part of the Garden string and expect it to be there when you do 'assertEquals(pruneDate,  "03/03/1993 21:22:13")' .... am I missing something?

**Comment by mra48** [comment]
Yeah so, in the test where i call assertEquals(pruneDate, "03/03/1993 21:22:13"), the 21:22:13 part is still in the creation of the garden  and thats why the change isnt showing up on github, because I didnt change that. The part where it is removed is in an earlier test which is showing up in github because it changed. I experimented with both types of dates (ones with and without times) just to make my tests more exhaustive. Does that clear things up?

**Comment by grselker** [comment]
Yes -- I will run the test now on my local machine.

**Comment by mra48** [comment]
Ok, I was hoping that you could to verify I did everything correctly. Let me know if you find anything wrong.

**Comment by grselker** [comment]
The good news is that the code still compiles ;) ...Yah -- I have your repository cloned on my machine so that I can test your stuff easily.

**Comment by grselker** [comment]
Did you change the constructor for Species? One of my tests for the Garden View is failing -- not failing, rather, it won't compile.

**Comment by grselker** [comment]
Species s = new Species("Tomato", "A plump red fruit", "Gracious sunbeams", "annual", new Date(2015, 5, 1), new Date(2015, 6, 1), color, size);

**Comment by mra48** [comment]
Yes, because the pruneDate is now a String instead of a Date object so the constructor is looking for a String and now a Date object. So instead of using "new Date(2015, 6, 1)", use "06/01/2015"

**Comment by grselker** [comment]
Would it be possible for you to update that and include the edit to that test in your pull request?

**Comment by mra48** [comment]
Update what? I changed everything already in all of the files so that pruneDate is a String

**Comment by mra48** [comment]
I updated the Species constructor as part of this pull request

**Comment by grselker** [comment]
It is in GardenViewTest.java, which it looks like you did not change.

**Comment by mra48** [comment]
I believe GardenViewTest.java is part of Chuck's code. Ill look into it or see if I can get in touch with Chuck

**Comment by grselker** [comment]
It is my code. It just needs that one constructor to be changed by you because I am code reviewing this.

**Comment by mra48** [comment]
Ok. Let me see what I can do. Give me one or two minutes

**Comment by grselker** [comment]
Absolutely -- sorry to bug you over this -- if I were not doing the code review, I would just make the change myself, but protocol ties my hands...

**Comment by mra48** [comment]
No its fine. I changed it and updated this pull request. Let me know about anything else

**Comment by grselker** [comment]
All tests compile and pass now. Let's merge this thing!

**Comment by mra48** [comment]
woooo!

**Pull request merged**
