### PR TITLE
helloWorld app, a good starting point

### PR DESCRIPTION
**Pull request by chuckie512**
This is the default setup as created by the IDE.  I feel it will be easier for everyone to create a branch off of this, as the IDE naively supports checkouts from github as a way to create a project.

### CODE REVIEW

**Comment by libertylocked** [comment]
i guess im doing QA now, lol.
and a quick note: master should always have the current working (and tested) version of the app
i'll see if i can have appveyor set up, so that we can do continuous integration

**Comment by chuckie512** [comment]
Haha you're not QA, you just said you wanted to deal with the merges so no one messes up the master.  It's tested don't worry

**Comment by libertylocked** [comment]
where is the solution file?

**Comment by chuckie512** [comment]
isn't that just a visual studio thing?
I'm using android studio.

**Comment by libertylocked** [comment]
never mind

**Pull request merged**
