### PR TITLE
adding and editing species info screen

### PR DESCRIPTION
**Pull request by chuckie512**
addit is the screen where modifications to the species and new species are added into the Garden data-structure by a user.

### CODE REVIEW

**Comment by grselker** [comment]
Hi Chuck, I am going to be reviewing this pull request this morning.

**Comment by grselker** [comment]
I am getting a build error:
protected void setDateText(String date){
        TextView textView = (TextView)findViewById(R.id.plant_date_viewer); <--- cannot find symbol variable plant_date_viewer
        textView.setText(date);
}

**Comment by chuckie512** [comment]
Oops, left some stuff in from working with the old Garden.java  should be fixed now

**Comment by grselker** [comment]
I like the activity for editing a species -- looks really good and seems to work. I tested all the fields and stuff. All the tests are passing as well.

**Comment by grselker** [comment]
I have looked over the diff, and it looks good, and I think there are enough comments. I am going to merge this.

**Pull request merged**
