### PR TITLE
Made changes to improve interfacing with classes

### PR DESCRIPTION
**Pull request by mra48**
These are the following changes.
1. plantDate and pruneDate are both Strings and they have both been
moved from the Species class to the Plant class.
2.  A new field, matTime, (maturationTime) has been added to the Species
class due to the request made for it in our last meeting
3.  The String that represents the garden in the gardenToString function
and stringToGarden has been reformatted to include all of the previous
changes. It is now parsed using the vertical bar, | ,
3a. The Format of the garden String is as follows:
"#species|speciesName|speciesDescription|speciesType (ex: 0 for annual,
1 for perennial, 2 for
tree)|speciesSunLevel|speciesColor|speciesSize|speciesMatTime|data for
next species|#plants|plantx|planty|plantPlantDate(using this
format:MM/dd/yyyy)|plantPruneDate(using this
format:MM/dd/yyyy)|plantSpeciesName|data for next plant"
4. Modified GardenViewTest.java to initialize the Species and Plant
based on the changes to the Species and Plant class
5. This probably goes without saying, but i modified GardenTest.java to accommodate all of these changes

### CODE REVIEW

**Comment by grselker** [comment]
Hi Muneeb, I am going to review your pull request now.

**Comment by grselker** [comment]
Ok -- so I just looked at the diff for the Files Changed, and most of it looks good, but something that we are NOT going to do is leave the species colors as bogus values. Try out these, they should be real colors.
Here is a Green color: -1511192065
Here is a Red color: -318163969
Here is a Yellow color: -305001985

If you need more, let me know.

**Comment by grselker** [comment]
The application fails to compile. These are the lines that appear to break the build.
ViewSpeciesInfoActivity.java
line 87 -- getPlantDate()
line 91 -- getPruneDate()
GardenView.java
line 125 -- addPlant()
line 140 -- new Plant()

**Comment by mra48** [comment]
Ok, I added the colors you listed to testGetSpeciesInfo() in GardenTest.java so check it out. I also tested it and it works as predicted

**Comment by grselker** [comment]
After discussion on Google Hangouts, Muneeb is not going to be the one to fix the build errors because it is going to cause messy merge conflicts. Chuck and I will fix these in our pull requests.

**Comment by grselker** [comment]
I can see that you added the colors to the testGetSpeciesInfo() -- now we have real and bogus colors covered.

**Comment by grselker** [comment]
Ok -- I have run GardenTest.java and it passes. I have found that in MainActivityTest.java,
testLoadDefaultGarden() and testLoadGarden() fail. #46 is changing how LoadDefaultGarden() and LoadGarden() work as it is, so I am going to let this go for this pull request, and #46 will fix these tests.

**Comment by grselker** [comment]
Muneeb, your changes look alright. I am going to merge this.

**Pull request merged**
