### PR TITLE
Fixed bug where rotating screen several times in a row crashed the Ga…

### PR DESCRIPTION
**Pull request by grselker**
…rden Drawing Activity

Solution: Setting the screenOrientation to landscape in the manifest file. This
forces the Garden Drawing Activity to be drawn as landscape.

Rotating the emulator screen rapidly no longer causes the Garden Drawing Activity
to crash.

### CODE REVIEW

**Comment by grselker** [comment]
This is a one-line addition to the manifest file. Try rotating the orientation of the screen several times in a row with the Garden Drawing Activity open (emulator and physical device if you have one) and make sure it doesn't crash.

**Comment by grselker** [comment]
I believe that this will fix #14. Please verify this as well.

**Comment by libertylocked** [comment]
This activity runs only in landscape while others runs on both landscape and portrait?

Maybe set the entire app to run in landscape?

**Comment by grselker** [comment]
After talking with Joe and Chuck on gmail, we all agree that it would be better to just add this small fix now because it is actually a bug fix, and leave changing the other activities for later.

**Comment by libertylocked** [comment]
the file changed in c5f2266420e30fad29ae41b71e995ee2bd12bfe7 is also in 9ea10dee4d76d6a6b5c7d111ea3136ba42507fa9 - with the same diff
should close this PR for duplication - only need to do #37

**Comment by grselker** [comment]
I suggest that we merge this pull request because this pull request specifically targets the bug. The reason it is in the other pull request is I did not want the bug in the app when I was working on #37. But if you are really opposed to that, go ahead and close this.

**Pull request merged**
