### PR TITLE
Added FileOperation.exists and FileOperation.delete and their tests

### PR DESCRIPTION
**Pull request by libertylocked**

### CODE REVIEW

**Comment by grselker** [comment]
Hi Wenchao. I am code reviewing this pull request now. If it is possible, please put a one-line description above each of the 3 new tests you added to FileOperationTest.java

All the file operation tests are failing due to permission denied. Do we have a solution to that yet?

All tests are passing except testFileOpExists -- the file4.txt was found

For testFileOpExists, I recommend saving to the file, checking if it exists, and then deleting the file and checking if it exists. It should be ok to use delete because there is another test for it already. The other option is to always perform a delete at the end of the test. Another option is to wipe the data on the emulator before running the test, which is no fun.

I wiped the data on the emulator, and it did not solve the problem.

**Comment by grselker** [comment]
All the file operation tests are failing due to permission denied. Do we have a solution to that yet?

**Comment by grselker** [comment]
All tests are passing except testFileOpExists -- the file4.txt was found

**Comment by grselker** [comment]
For testFileOpExists, I recommend saving to the file, checking if it exists, and then deleting the file and checking if it exists.

**Comment by grselker** [comment]
It should be ok to use delete because there is another test for it already.

**Comment by grselker** [comment]
The other option is to always perform a delete at the end of the test.

**Comment by grselker** [comment]
Another option is to wipe the data on the emulator before running the test, which is no fun.

**Comment by grselker** [comment]
I wiped the data on the emulator, and it did not solve the problem.

**Comment by libertylocked** [comment]
I've updated the tests.
delete() and exists() are tested in one test now

**Pull request merged**
