### PR TITLE
Feature/add existing plant

### PR DESCRIPTION
**Pull request by grselker**
Allows you to long press and existing plant do the following:
Move, and then Confirm to set new location
Add Another
Remove, and then Confirm the deletion
Cancel, and roll back a Remove if it was not Confirmed

### CODE REVIEW

**Comment by grselker** [comment]
This feature should be ready to test now.

**Comment by grselker** [comment]
All tests should pass now.

**Comment by libertylocked** [comment]
The app has some serious defects with the back button in general
e.g. clicking "view species list" after clicking "add to garden", it can lead to unexpected results

Also if user clicked confirm without tapping anywhere on screen, the circle is added to (0,0). Then it is impossible to long press such circle.

**Comment by grselker** [comment]
Wenchao -- I think I know how to fix the confirm button issue. I will push another commit to fix it as soon as possible.

**Comment by grselker** [comment]
I believe that I have fixed the problem with the problem with the Confirm button.

**Comment by libertylocked** [comment]
sorry clicked the wrong button

**Pull request merged**
