### PR TITLE
removed old garden dir from src

### PR DESCRIPTION
**Pull request by chuckie512**
removed the garden directory from the src directory since garden has been moved to main

### CODE REVIEW

**Comment by grselker** [comment]
I see no reason why this cannot be merged.

**Comment by chuckie512** [comment]
@grselker I just want to make sure that I didn't screw something up for everyone else.  If someone can checkout the branch and make sure it still builds, tests still pass and no other errors, then they can merge it

**Comment by grselker** [comment]
I will do that.

**Comment by grselker** [comment]
Application builds and runs like a champ. All tests pass, and I did not find any other errors. I am going to merge this guy.

**Pull request merged**
