### PR TITLE
Added tons of comments and many more tests

### PR DESCRIPTION
**Pull request by mra48**
Also fixed some bugs thanks to the extra testing including things that
might have cause null pointer exceptions like trying to reference a null
pointer when returning a date object in getSpeciesInfo. These are additions and changes from the latest versions of these files from the group repository so you dont need to worry about making sure if I was working on older versions or not. This is the latest representation of these 5 files.

### CODE REVIEW

**Comment by chuckie512** [comment]
comments look good and address the issues in #20

**Comment by grselker** [comment]
Hello James Bond. I am beginning your code review now.

**Comment by grselker** [comment]
Code compiles and the app runs. This is good news.

**Comment by grselker** [comment]
I ran all the unit tests, and testFileSaveLoadLongString as well as testFileSaveLoadMultiLineString failed.
I don't think these are related to you changes, but they must be investigated perhaps as a separate issue. 

Unfortunately, testCreateGarden failed:
junit.framework.ComparisonFailure: expected:<it's a plant> but was:<null>
at com.cs1530_group1.gardenapp.GardenTest.testCreateGarden(GardenTest.java:304)

**Comment by grselker** [comment]
I think it is a problem with getSpecies(String speciesName) because I changed it to just return s instead of a copy and the test passed.

**Comment by grselker** [comment]
I think that the comments as a whole are pretty good. I would like to see a short description of Plant and Species, though. Once these specific comments are added, and the failing test (testCreateGarden) is fixed, this branch can be merged. This will fulfill #20 Garden classes need javadoc and comments.

**Comment by mra48** [comment]
The test testCreateGarden wasnt created by me, it was created by chuck and it probably worked for him. Ill check with him about that. Ill try to add more comments that describe the Plant and species class

**Comment by grselker** [comment]
Ah...yah -- you don't need to go overboard with the Plant and Species classes because there's not much there, but I thought it would just be good.

**Comment by mra48** [comment]
Ok. I added the comments and i fixed the bug to only return s. I also made sure all of the tests worked, even chucks so we dont have to bother him. I dont think you should upload anything with garden.java because i made the changes to fix the bugs you mentioned and maybe you could take a look after i upload them. I will upload the files shortly after i figure out how to update my pull request

**Comment by mra48** [comment]
Ok. I updated the pull request. It gets automatically updated as soon as i push. Its listed right above this comment. So check out the changes and let me know what you think

**Comment by grselker** [comment]
Changes and additional comments look good. The failing test has been fixed and the app still runs. I am going to merge this pull request now and close #20.

**Pull request merged**
